project_id = "qzzyfohzoxiefwbmtclt"

[functions.kommo-webhook]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.admin-data]
verify_jwt = false

[functions.get-client-ip]
verify_jwt = false

[functions.notify-lead]
verify_jwt = false

[functions.meta-ads-resolve]
verify_jwt = false

[functions.web-push]
verify_jwt = false

[functions.meta-ads-sync]
verify_jwt = false

[functions.meta-capi]
verify_jwt = false

[functions.meta-ads-cron]
verify_jwt = false

[functions.landing-hit]
verify_jwt = false

[functions.ai-admin-assistant]
verify_jwt = false
